# Generated by Django 4.2.1 on 2023-08-30 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('web', models.URLField()),
                ('tel', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name_plural': 'Distribuidores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('descripcion', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware')], max_length=8)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.distribuidor')),
            ],
        ),
    ]
