# Generated by Django 4.2.1 on 2023-08-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
