# Generated by Django 4.2.1 on 2023-11-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Remoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('foto', models.ImageField(null=True, upload_to='imagenes')),
                ('tipo', models.CharField(choices=[('smart', 'Smart'), ('no_smart', 'No_Smart')], max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Remotos',
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='distribuidor',
        ),
        migrations.DeleteModel(
            name='Distribuidor',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
