# Generated by Django 4.2.1 on 2024-01-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_marca_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoto',
            name='tipo',
            field=models.CharField(choices=[('tv_smart', 'TV Smart'), ('tv', 'TV'), ('canalera', 'Canalera'), ('directv', 'Directv'), ('smartbox', 'Smartbox')], max_length=10),
        ),
    ]
